// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-0cQJezuu9sgSlVUQWISqdOiIC-U9Bvc',
    appId: '1:246129798935:web:e62942d57fc333e90fd152',
    messagingSenderId: '246129798935',
    projectId: 'study-flutter-11-01-firebase',
    authDomain: 'study-flutter-11-01-firebase.firebaseapp.com',
    storageBucket: 'study-flutter-11-01-firebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTJypC0Olh83Et-PkFXOh4pB1Lfsiv8nk',
    appId: '1:246129798935:android:92e62d0491d0cb6f0fd152',
    messagingSenderId: '246129798935',
    projectId: 'study-flutter-11-01-firebase',
    storageBucket: 'study-flutter-11-01-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3mOPlkt8X0PHf5icBVLaNxr0TVj9gx3U',
    appId: '1:246129798935:ios:76b701f2154e476c0fd152',
    messagingSenderId: '246129798935',
    projectId: 'study-flutter-11-01-firebase',
    storageBucket: 'study-flutter-11-01-firebase.appspot.com',
    iosClientId: '246129798935-gtq48229s51371ec2d6bgaagoht4p4qi.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyFlutter11Codingchef01Firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3mOPlkt8X0PHf5icBVLaNxr0TVj9gx3U',
    appId: '1:246129798935:ios:39d879becaa692330fd152',
    messagingSenderId: '246129798935',
    projectId: 'study-flutter-11-01-firebase',
    storageBucket: 'study-flutter-11-01-firebase.appspot.com',
    iosClientId: '246129798935-757489su245sp76m0gs5de5teovh1h7r.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyFlutter11Codingchef01Firebase.RunnerTests',
  );
}
